
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Wed Feb 07 11:17:34 CET 2024
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CHAR_CONST = 47;
  public static final int DIVIDE = 14;
  public static final int LBRACKET = 33;
  public static final int INCREMENT = 25;
  public static final int CONST = 3;
  public static final int EQUALS = 16;
  public static final int NAMESPACE = 10;
  public static final int CONTINUE = 44;
  public static final int LPAREN = 31;
  public static final int FOR = 38;
  public static final int MINUS = 12;
  public static final int DECREMENT = 26;
  public static final int GREATER_THAN = 18;
  public static final int STATIC = 9;
  public static final int RPAREN = 32;
  public static final int SEMICOLON = 27;
  public static final int AND = 22;
  public static final int OR = 23;
  public static final int COMMA = 29;
  public static final int CLASS = 43;
  public static final int LESS_EQUAL = 21;
  public static final int PLUS = 11;
  public static final int MULTIPLY = 13;
  public static final int IF = 41;
  public static final int ASSIGN = 24;
  public static final int DOT = 30;
  public static final int EOF = 0;
  public static final int RETURN = 7;
  public static final int RBRACKET = 34;
  public static final int GREATER_EQUAL = 19;
  public static final int NEW = 4;
  public static final int error = 1;
  public static final int PROGRAM = 2;
  public static final int MODULO = 15;
  public static final int NUMBER = 45;
  public static final int IDENT = 46;
  public static final int BREAK = 42;
  public static final int VOID = 8;
  public static final int ARROW = 37;
  public static final int COLON = 28;
  public static final int ELSE = 40;
  public static final int LBRACE = 35;
  public static final int READ = 6;
  public static final int NOT_EQUALS = 17;
  public static final int RBRACE = 36;
  public static final int EXTENDS = 39;
  public static final int BOOL_CONST = 48;
  public static final int LESS_THAN = 20;
  public static final int PRINT = 5;
}

