package rs.ac.bg.etf.pp1;


public class sym_old {
    public static final int PROGRAM = 1;
    public static final int BREAK = 2;
    public static final int CLASS = 3;
    public static final int ELSE = 4;
    public static final int CONST = 5;
    public static final int IF = 6;
    public static final int NEW = 7;
    public static final int PRINT = 8;
    public static final int READ = 9;
    public static final int RETURN = 10;
    public static final int VOID = 11;
    public static final int EXTENDS = 12;
    public static final int CONTINUE = 13;
    public static final int FOR = 14;
    public static final int STATIC = 15;
    public static final int NAMESPACE = 16;
    public static final int PLUS = 17;
    public static final int MINUS = 18;
    public static final int MULTIPLY = 19;
    public static final int DIVIDE = 20;
    public static final int MODULO = 21;
    public static final int EQUALS = 22;
    public static final int NOT_EQUALS = 23;
    public static final int GREATER_THAN = 24;
    public static final int GREATER_EQUAL = 25;
    public static final int LESS_THAN = 26;
    public static final int LESS_EQUAL = 27;
    public static final int AND = 28;
    public static final int OR = 29;
    public static final int ASSIGN = 30;
    public static final int INCREMENT = 31;
    public static final int DECREMENT = 32;
    public static final int SEMICOLON = 33;
    public static final int COLON = 34;
    public static final int COMMA = 35;
    public static final int DOT = 36;
    public static final int LPAREN = 37;
    public static final int RPAREN = 38;
    public static final int LBRACKET = 39;
    public static final int RBRACKET = 40;
    public static final int LBRACE = 41;
    public static final int RBRACE = 42;
    public static final int ARROW = 43;
    public static final int BOOL_CONST = 44;
    public static final int CHAR_CONST = 45;
    public static final int NUMBER = 46;
    public static final int IDENT = 47;
    public static final int EOF = 0;
}
